### ISSUE TITLE
Use `params` in `block-index`

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subgraph-cosmos-proposals#4]
- [x] add `cosmos_proposals` to key in block-index
  - issue is because we're using `params` twice for different usecases
  - additional issue is we are forced to use `query` in blockFilter
- [x] refactor `block-index` to leverage the use of `params`

```yaml
blockFilter:
  module: block_index:index_blocks
  query:
    string: "cosmos_proposals"
    params: false
```
